id = "zig"
name = "Zig"
description = "First class Zig support for the Zed editor."
version = "0.1.0"
schema_version = 1
authors = ["viable <hi@viable.gg>"]
repository = "https://github.com/nuiipointerexception/zed_zig"
snippets = "./snippets/zig.json"

[language_servers.zls]
name = "zls"
language = "Zig"

[grammars.zig]
repository = "https://github.com/nuIIpointerexception/tree-sitter-zig"
commit = "eb7d58c2dc4fbeea4745019dee8df013034ae66b"
